apiVersion: v1
kind: Pod
metadata:
  name: beverages
spec:
  containers:
  - name: pepsi
    image: "registry.access.redhat.com/ubi9/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - mountPath: "/volume"
        name: shared-volume
    securityContext:
      seLinuxOptions:
        user: system_u
        role: system_r
        type: container_t
        level: s0:c1,c3
  - name: coke
    image: "registry.access.redhat.com/ubi9/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - mountPath: "/volume"
        name: shared-volume
    securityContext:
      seLinuxOptions:
        user: system_u
        role: system_r
        type: container_t
        level: s0:c3,c6
  volumes:
    - name: shared-volume
      emptyDir: {}
    - securityContext:
      seLinuxOptions:
        user: system_u
        role: system_r
        type: container_t
        level: s0:c3
  restartPolicy: Never
